name: .NETdep
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal 
    - name: Stop demo
      run: appcmd stop sites "demo"
    - name: Publish Release
      run: dotnet publish demo --configuration Release -o c:\wwwroot\demo
    - name: Start demo
      run: appcmd start sites "demo"
